name: solura_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  local_auth: ^3.0.0
  flutter_secure_storage: ^10.0.0
  cupertino_icons: ^1.0.8
  intl: ^0.18.0
  fl_chart: ^1.1.1
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.0
  video_player: ^2.8.3
  chewie: ^1.5.0
  image_picker: ^1.0.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png

flutter_native_splash:
  color: "#ffffff"               # background
  image: "assets/icon/icon.png"  # logo
  android: true
  ios: true
  android_gravity: center        # fills and centers logo
  ios_content_mode: scaleAspectFill
  fullscreen: true



